### ISSUE TITLE
Prophesee EVK2 Gen41 Error

### ISSUE THREAD

**Issue by mohammedsalah98** [berndpfrommer/metavision_ros_driver#1]
Hi,

I have received this error:
SyntaxError: Non-ASCII character '\xe2' in file /home/m123/metavision_ros_driver_ws/src/metavision_ros_driver/cfg/MetaVisionDyn.cfg on line 14, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
and solved it by removing the comments in the cfg file.
The main issue is that once I plug in my prophesee EVK2 gen41 I get this error and run the nodes on ROS1:
[event_camera-2] process has died [pid 13167, exit code -11, cmd /home/m123/metavision_ros_driver_ws/devel/lib/metavision_ros_driver/driver_node __name:=event_camera __log:=/home/m123/.ros/log/9f737452-0d9d-11ed-b622-347df657bc28/event_camera-2.log].
log file: /home/m123/.ros/log/9f737452-0d9d-11ed-b622-347df657bc28/event_camera-2*.log
May you assist in this issue please, thanks. I have tried this on ubuntu 18/ROS melodic and ubuntu 20/ROS noetic.

**Comment by k-chaney** [comment]
@mohammedsalah98 Could you upload the log file that is referenced?

**Comment by mohammedsalah98** [comment]
These are the log files that were generated after running the node:


[master.log](https://github.com/berndpfrommer/metavision_ros_driver/files/9199348/master.log)
[roslaunch-m123-Nitro-AN515-55-20855.log](https://github.com/berndpfrommer/metavision_ros_driver/files/9199349/roslaunch-m123-Nitro-AN515-55-20855.log)
[rosout.log](https://github.com/berndpfrommer/metavision_ros_driver/files/9199350/rosout.log)
[rosout-1-stdout.log](https://github.com/berndpfrommer/metavision_ros_driver/files/9199351/rosout-1-stdout.log)


roslaunch output:
[roslaunch][INFO] 2022-07-27 17:36:40,834: Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
[roslaunch][INFO] 2022-07-27 17:36:40,836: Done checking log file disk usage. Usage is <1GB.
[roslaunch][INFO] 2022-07-27 17:36:40,837: roslaunch starting with args ['/opt/ros/melodic/bin/roslaunch', 'metavision_ros_driver', 'driver_node.launch']
[roslaunch][INFO] 2022-07-27 17:36:40,837: roslaunch env is {'LC_NUMERIC': 'ar_AE.UTF-8', 'CONDA_PYTHON_EXE': '/home/m123/anaconda3/bin/python', 'MV_HAL_PLUGIN_PATH': '/home/m123/openeb/build/lib/metavision/hal/plugins', 'QT4_IM_MODULE': 'xim', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'PKG_CONFIG_PATH': '/home/m123/metavision_ros_driver_ws/devel/lib/pkgconfig:/opt/ros/melodic/lib/pkgconfig', '_CE_M': '', 'XDG_CURRENT_DESKTOP': 'ubuntu:GNOME', 'LC_PAPER': 'ar_AE.UTF-8', 'ROSLISP_PACKAGE_DIRECTORIES': '/home/m123/metavision_ros_driver_ws/devel/share/common-lisp', 'QT_IM_MODULE': 'ibus', 'LOGNAME': 'm123', 'USER': 'm123', 'PATH': '/opt/ros/melodic/bin:/home/m123/openeb/build/bin:/home/m123/anaconda3/bin:/home/m123/anaconda3/condabin:/home/m123/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'XDG_VTNR': '2', 'HOME': '/home/m123', 'CMAKE_PREFIX_PATH': '/home/m123/metavision_ros_driver_ws/devel:/opt/ros/melodic', 'DISPLAY': ':0', 'SSH_AGENT_PID': '1652', 'LANG': 'en_US.UTF-8', 'CONDA_SHLVL': '1', 'SHELL': '/bin/bash', 'ROS_LOG_FILENAME': '/home/m123/.ros/log/2582f37a-0db1-11ed-b622-347df657bc28/roslaunch-m123-Nitro-AN515-55-20855.log', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'SESSION_MANAGER': 'local/m123-Nitro-AN515-55:@/tmp/.ICE-unix/1557,unix/m123-Nitro-AN515-55:/tmp/.ICE-unix/1557', 'LC_MEASUREMENT': 'ar_AE.UTF-8', 'ROS_DISTRO': 'melodic', 'CONDA_PREFIX': '/home/m123/anaconda3', 'QT_ACCESSIBILITY': '1', 'LD_LIBRARY_PATH': '/home/m123/metavision_ros_driver_ws/devel/lib:/opt/ros/melodic/lib', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'CLUTTER_IM_MODULE': 'xim', 'TEXTDOMAIN': 'im-config', '_': '/opt/ros/melodic/bin/roslaunch', 'CONDA_DEFAULT_ENV': 'base', 'XMODIFIERS': '@im=ibus', 'ROS_MASTER_URI': 'http://localhost:11311', 'XDG_RUNTIME_DIR': '/run/user/1000', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'ROS_PYTHON_VERSION': '2', 'USERNAME': 'm123', 'XDG_SESSION_DESKTOP': 'ubuntu', '_CE_CONDA': '', 'ROS_VERSION': '1', 'GTK_IM_MODULE': 'ibus', 'LC_ADDRESS': 'ar_AE.UTF-8', 'PYTHONPATH': '/home/m123/metavision_ros_driver_ws/devel/lib/python2.7/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages:/home/m123/openeb/build/py3:/home/m123/openeb/sdk/modules/core/python/pypkg:/home/m123/openeb/sdk/modules/ml/python/pypkg:/home/m123/openeb/sdk/modules/ml/python_extended/pypkg:/home/m123/openeb/sdk/modules/core_ml/python/pypkg', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'SHLVL': '1', 'TERM': 'xterm-256color', 'ROS_ROOT': '/opt/ros/melodic/share/ros', 'GDMSESSION': 'ubuntu', 'IM_CONFIG_PHASE': '2', 'TEXTDOMAINDIR': '/usr/share/locale/', 'GNOME_SHELL_SESSION_MODE': 'ubuntu', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/etc/xdg', 'ROS_PACKAGE_PATH': '/home/m123/metavision_ros_driver_ws/src/dvs_msgs:/home/m123/metavision_ros_driver_ws/src/event_array_msgs:/home/m123/metavision_ros_driver_ws/src/prophesee_event_msgs:/home/m123/metavision_ros_driver_ws/src/metavision_ros_driver:/opt/ros/melodic/share', 'CONDA_PROMPT_MODIFIER': '(base) ', 'XDG_SESSION_ID': '2', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'WINDOWPATH': '2', 'GNOME_TERMINAL_SERVICE': ':1.315', 'LC_IDENTIFICATION': 'ar_AE.UTF-8', 'DESKTOP_SESSION': 'ubuntu', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'GTK_MODULES': 'gail:atk-bridge', 'VTE_VERSION': '5202', 'XDG_SESSION_TYPE': 'x11', 'XDG_SEAT': 'seat0', 'OLDPWD': '/home/m123', 'LC_TELEPHONE': 'ar_AE.UTF-8', 'LC_MONETARY': 'ar_AE.UTF-8', 'PWD': '/home/m123/metavision_ros_driver_ws', 'ROS_ETC_DIR': '/opt/ros/melodic/etc/ros', 'COLORTERM': 'truecolor', 'LC_NAME': 'ar_AE.UTF-8', 'XDG_MENU_PREFIX': 'gnome-', 'LC_TIME': 'ar_AE.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'CONDA_EXE': '/home/m123/anaconda3/bin/conda', 'GNOME_TERMINAL_SCREEN': '/org/gnome/Terminal/screen/e9b3628e_20c2_4ab9_9b4c_e0465cef6780'}
[roslaunch][INFO] 2022-07-27 17:36:40,837: starting in server mode
[roslaunch.parent][INFO] 2022-07-27 17:36:40,837: starting roslaunch parent run
[roslaunch][INFO] 2022-07-27 17:36:40,837: loading roscore config file /opt/ros/melodic/etc/ros/roscore.xml
[roslaunch][INFO] 2022-07-27 17:36:41,147: Added core node of type [rosout/rosout] in namespace [/]
[roslaunch.config][INFO] 2022-07-27 17:36:41,147: loading config file /home/m123/metavision_ros_driver_ws/src/metavision_ros_driver/launch/driver_node.launch
[roslaunch][INFO] 2022-07-27 17:36:41,175: Added node of type [metavision_ros_driver/driver_node] in namespace [/]
[roslaunch][INFO] 2022-07-27 17:36:41,175: ... selected machine [] for node of type [metavision_ros_driver/driver_node]
[roslaunch.pmon][INFO] 2022-07-27 17:36:41,176: start_process_monitor: creating ProcessMonitor
[roslaunch.pmon][INFO] 2022-07-27 17:36:41,176: created process monitor <ProcessMonitor(ProcessMonitor-1, initial daemon)>
[roslaunch.pmon][INFO] 2022-07-27 17:36:41,176: start_process_monitor: ProcessMonitor started
[roslaunch.parent][INFO] 2022-07-27 17:36:41,176: starting parent XML-RPC server
[roslaunch.server][INFO] 2022-07-27 17:36:41,176: starting roslaunch XML-RPC server
[roslaunch.server][INFO] 2022-07-27 17:36:41,176: waiting for roslaunch XML-RPC server to initialize
[xmlrpc][INFO] 2022-07-27 17:36:41,176: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-07-27 17:36:41,176: Started XML-RPC server [http://m123-Nitro-AN515-55:43333/]
[xmlrpc][INFO] 2022-07-27 17:36:41,177: xml rpc node: starting XML-RPC server
[roslaunch][INFO] 2022-07-27 17:36:41,187: started roslaunch server http://m123-Nitro-AN515-55:43333/
[roslaunch.parent][INFO] 2022-07-27 17:36:41,187: ... parent XML-RPC server started
[roslaunch][INFO] 2022-07-27 17:36:41,188: master.is_running[http://localhost:11311]
[roslaunch][INFO] 2022-07-27 17:36:41,188: auto-starting new master
[roslaunch][INFO] 2022-07-27 17:36:41,188: create_master_process: rosmaster, /opt/ros/melodic/share/ros, 11311, 3, None, False
[roslaunch][INFO] 2022-07-27 17:36:41,188: process[master]: launching with args [['rosmaster', '--core', '-p', '11311', '-w', '3']]
[roslaunch.pmon][INFO] 2022-07-27 17:36:41,188: ProcessMonitor.register[master]
[roslaunch.pmon][INFO] 2022-07-27 17:36:41,188: ProcessMonitor.register[master] complete
[roslaunch][INFO] 2022-07-27 17:36:41,188: process[master]: starting os process
[roslaunch][INFO] 2022-07-27 17:36:41,188: process[master]: start w/ args [['rosmaster', '--core', '-p', '11311', '-w', '3', '__log:=/home/m123/.ros/log/2582f37a-0db1-11ed-b622-347df657bc28/master.log']]
[roslaunch][INFO] 2022-07-27 17:36:41,188: process[master]: cwd will be [/home/m123/.ros]
[roslaunch][INFO] 2022-07-27 17:36:41,191: process[master]: started with pid [20877]
[roslaunch][INFO] 2022-07-27 17:36:41,191: master.is_running[http://localhost:11311]
[roslaunch][INFO] 2022-07-27 17:36:41,291: master.is_running[http://localhost:11311]
[roslaunch][INFO] 2022-07-27 17:36:41,392: master.is_running[http://localhost:11311]
[roslaunch][INFO] 2022-07-27 17:36:41,393: master.is_running[http://localhost:11311]
[roslaunch][INFO] 2022-07-27 17:36:41,394: ROS_MASTER_URI=http://localhost:11311
[roslaunch][INFO] 2022-07-27 17:36:41,395: setting /run_id to 2582f37a-0db1-11ed-b622-347df657bc28
[roslaunch][INFO] 2022-07-27 17:36:41,395: setting /roslaunch/uris/host_m123_nitro_an515_55__43333' to http://m123-Nitro-AN515-55:43333/
[roslaunch][INFO] 2022-07-27 17:36:41,397: ... preparing to launch node of type [rosout/rosout]
[roslaunch][INFO] 2022-07-27 17:36:41,397: create_node_process: package[rosout] type[rosout] machine[Machine(name[] env_loader[None] address[localhost] ssh_port[22] user[None] assignable[True] timeout[10.0])] master_uri[http://localhost:11311]
[roslaunch][INFO] 2022-07-27 17:36:41,397: process[rosout-1]: env[{'LC_NUMERIC': 'ar_AE.UTF-8', 'CONDA_PYTHON_EXE': '/home/m123/anaconda3/bin/python', 'ROS_DISTRO': 'melodic', 'GNOME_TERMINAL_SCREEN': '/org/gnome/Terminal/screen/e9b3628e_20c2_4ab9_9b4c_e0465cef6780', 'QT4_IM_MODULE': 'xim', 'WINDOWPATH': '2', 'COLORTERM': 'truecolor', '_CE_M': '', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'LC_PAPER': 'ar_AE.UTF-8', 'ROSLISP_PACKAGE_DIRECTORIES': '/home/m123/metavision_ros_driver_ws/devel/share/common-lisp', 'QT_IM_MODULE': 'ibus', 'LOGNAME': 'm123', 'USER': 'm123', 'PATH': '/opt/ros/melodic/bin:/home/m123/openeb/build/bin:/home/m123/anaconda3/bin:/home/m123/anaconda3/condabin:/home/m123/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'XDG_VTNR': '2', 'HOME': '/home/m123', 'CMAKE_PREFIX_PATH': '/home/m123/metavision_ros_driver_ws/devel:/opt/ros/melodic', 'DISPLAY': ':0', 'SSH_AGENT_PID': '1652', 'LANG': 'en_US.UTF-8', 'CONDA_SHLVL': '1', 'SHELL': '/bin/bash', 'ROS_LOG_FILENAME': '/home/m123/.ros/log/2582f37a-0db1-11ed-b622-347df657bc28/roslaunch-m123-Nitro-AN515-55-20855.log', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'SESSION_MANAGER': 'local/m123-Nitro-AN515-55:@/tmp/.ICE-unix/1557,unix/m123-Nitro-AN515-55:/tmp/.ICE-unix/1557', 'LC_MEASUREMENT': 'ar_AE.UTF-8', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'CONDA_PREFIX': '/home/m123/anaconda3', 'CLUTTER_IM_MODULE': 'xim', 'MV_HAL_PLUGIN_PATH': '/home/m123/openeb/build/lib/metavision/hal/plugins', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'QT_ACCESSIBILITY': '1', 'TEXTDOMAIN': 'im-config', 'CONDA_DEFAULT_ENV': 'base', 'XMODIFIERS': '@im=ibus', 'ROS_ETC_DIR': '/opt/ros/melodic/etc/ros', 'CONDA_PROMPT_MODIFIER': '(base) ', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'ROS_PYTHON_VERSION': '2', 'LC_MONETARY': 'ar_AE.UTF-8', 'USERNAME': 'm123', 'XDG_SESSION_DESKTOP': 'ubuntu', '_CE_CONDA': '', 'XDG_RUNTIME_DIR': '/run/user/1000', 'LC_IDENTIFICATION': 'ar_AE.UTF-8', 'LC_ADDRESS': 'ar_AE.UTF-8', 'PYTHONPATH': '/home/m123/metavision_ros_driver_ws/devel/lib/python2.7/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages:/home/m123/openeb/build/py3:/home/m123/openeb/sdk/modules/core/python/pypkg:/home/m123/openeb/sdk/modules/ml/python/pypkg:/home/m123/openeb/sdk/modules/ml/python_extended/pypkg:/home/m123/openeb/sdk/modules/core_ml/python/pypkg', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'TERM': 'xterm-256color', 'ROS_ROOT': '/opt/ros/melodic/share/ros', 'GDMSESSION': 'ubuntu', 'IM_CONFIG_PHASE': '2', 'TEXTDOMAINDIR': '/usr/share/locale/', 'GNOME_SHELL_SESSION_MODE': 'ubuntu', 'DESKTOP_SESSION': 'ubuntu', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop', 'PKG_CONFIG_PATH': '/home/m123/metavision_ros_driver_ws/devel/lib/pkgconfig:/opt/ros/melodic/lib/pkgconfig', 'ROS_PACKAGE_PATH': '/home/m123/metavision_ros_driver_ws/src/dvs_msgs:/home/m123/metavision_ros_driver_ws/src/event_array_msgs:/home/m123/metavision_ros_driver_ws/src/prophesee_event_msgs:/home/m123/metavision_ros_driver_ws/src/metavision_ros_driver:/opt/ros/melodic/share', 'XDG_CURRENT_DESKTOP': 'ubuntu:GNOME', 'XDG_SESSION_ID': '2', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', '_': '/opt/ros/melodic/bin/roslaunch', 'GTK_MODULES': 'gail:atk-bridge', 'GTK_IM_MODULE': 'ibus', 'LD_LIBRARY_PATH': '/home/m123/metavision_ros_driver_ws/devel/lib:/opt/ros/melodic/lib', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/etc/xdg', 'GNOME_TERMINAL_SERVICE': ':1.315', 'VTE_VERSION': '5202', 'XDG_SESSION_TYPE': 'x11', 'OLDPWD': '/home/m123', 'LC_TELEPHONE': 'ar_AE.UTF-8', 'SHLVL': '1', 'PWD': '/home/m123/metavision_ros_driver_ws', 'ROS_MASTER_URI': 'http://localhost:11311', 'ROS_VERSION': '1', 'LC_NAME': 'ar_AE.UTF-8', 'XDG_MENU_PREFIX': 'gnome-', 'LC_TIME': 'ar_AE.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'CONDA_EXE': '/home/m123/anaconda3/bin/conda', 'XDG_SEAT': 'seat0'}]
[roslaunch][INFO] 2022-07-27 17:36:41,421: process[rosout-1]: args[[u'/opt/ros/melodic/lib/rosout/rosout', u'__name:=rosout']]
[roslaunch][INFO] 2022-07-27 17:36:41,421: ... created process [rosout-1]
[roslaunch.pmon][INFO] 2022-07-27 17:36:41,421: ProcessMonitor.register[rosout-1]
[roslaunch.pmon][INFO] 2022-07-27 17:36:41,421: ProcessMonitor.register[rosout-1] complete
[roslaunch][INFO] 2022-07-27 17:36:41,421: ... registered process [rosout-1]
[roslaunch][INFO] 2022-07-27 17:36:41,421: process[rosout-1]: starting os process
[roslaunch][INFO] 2022-07-27 17:36:41,421: process[rosout-1]: start w/ args [[u'/opt/ros/melodic/lib/rosout/rosout', u'__name:=rosout', u'__log:=/home/m123/.ros/log/2582f37a-0db1-11ed-b622-347df657bc28/rosout-1.log']]
[roslaunch][INFO] 2022-07-27 17:36:41,421: process[rosout-1]: cwd will be [/home/m123/.ros]
[roslaunch][INFO] 2022-07-27 17:36:41,424: process[rosout-1]: started with pid [20899]
[roslaunch][INFO] 2022-07-27 17:36:41,424: ... successfully launched [rosout-1]
[roslaunch][INFO] 2022-07-27 17:36:41,424: load_parameters starting ...
[roslaunch][INFO] 2022-07-27 17:36:41,433: ... load_parameters complete
[roslaunch][INFO] 2022-07-27 17:36:41,433: launch_nodes: launching local nodes ...
[roslaunch][INFO] 2022-07-27 17:36:41,433: ... preparing to launch node of type [metavision_ros_driver/driver_node]
[roslaunch][INFO] 2022-07-27 17:36:41,433: create_node_process: package[metavision_ros_driver] type[driver_node] machine[Machine(name[] env_loader[None] address[localhost] ssh_port[22] user[None] assignable[True] timeout[10.0])] master_uri[http://localhost:11311]
[roslaunch][INFO] 2022-07-27 17:36:41,433: process[event_camera-2]: env[{'LC_NUMERIC': 'ar_AE.UTF-8', 'CONDA_PYTHON_EXE': '/home/m123/anaconda3/bin/python', 'ROS_DISTRO': 'melodic', 'GNOME_TERMINAL_SCREEN': '/org/gnome/Terminal/screen/e9b3628e_20c2_4ab9_9b4c_e0465cef6780', 'QT4_IM_MODULE': 'xim', 'WINDOWPATH': '2', 'COLORTERM': 'truecolor', '_CE_M': '', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'LC_PAPER': 'ar_AE.UTF-8', 'ROSLISP_PACKAGE_DIRECTORIES': '/home/m123/metavision_ros_driver_ws/devel/share/common-lisp', 'QT_IM_MODULE': 'ibus', 'LOGNAME': 'm123', 'USER': 'm123', 'PATH': '/opt/ros/melodic/bin:/home/m123/openeb/build/bin:/home/m123/anaconda3/bin:/home/m123/anaconda3/condabin:/home/m123/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'XDG_VTNR': '2', 'HOME': '/home/m123', 'CMAKE_PREFIX_PATH': '/home/m123/metavision_ros_driver_ws/devel:/opt/ros/melodic', 'DISPLAY': ':0', 'SSH_AGENT_PID': '1652', 'LANG': 'en_US.UTF-8', 'CONDA_SHLVL': '1', 'SHELL': '/bin/bash', 'ROS_LOG_FILENAME': '/home/m123/.ros/log/2582f37a-0db1-11ed-b622-347df657bc28/roslaunch-m123-Nitro-AN515-55-20855.log', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'SESSION_MANAGER': 'local/m123-Nitro-AN515-55:@/tmp/.ICE-unix/1557,unix/m123-Nitro-AN515-55:/tmp/.ICE-unix/1557', 'LC_MEASUREMENT': 'ar_AE.UTF-8', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'CONDA_PREFIX': '/home/m123/anaconda3', 'CLUTTER_IM_MODULE': 'xim', 'MV_HAL_PLUGIN_PATH': '/home/m123/openeb/build/lib/metavision/hal/plugins', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'QT_ACCESSIBILITY': '1', 'TEXTDOMAIN': 'im-config', 'CONDA_DEFAULT_ENV': 'base', 'XMODIFIERS': '@im=ibus', 'ROS_ETC_DIR': '/opt/ros/melodic/etc/ros', 'CONDA_PROMPT_MODIFIER': '(base) ', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'ROS_PYTHON_VERSION': '2', 'LC_MONETARY': 'ar_AE.UTF-8', 'USERNAME': 'm123', 'XDG_SESSION_DESKTOP': 'ubuntu', '_CE_CONDA': '', 'XDG_RUNTIME_DIR': '/run/user/1000', 'LC_IDENTIFICATION': 'ar_AE.UTF-8', 'LC_ADDRESS': 'ar_AE.UTF-8', 'PYTHONPATH': '/home/m123/metavision_ros_driver_ws/devel/lib/python2.7/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages:/home/m123/openeb/build/py3:/home/m123/openeb/sdk/modules/core/python/pypkg:/home/m123/openeb/sdk/modules/ml/python/pypkg:/home/m123/openeb/sdk/modules/ml/python_extended/pypkg:/home/m123/openeb/sdk/modules/core_ml/python/pypkg', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'TERM': 'xterm-256color', 'ROS_ROOT': '/opt/ros/melodic/share/ros', 'GDMSESSION': 'ubuntu', 'IM_CONFIG_PHASE': '2', 'TEXTDOMAINDIR': '/usr/share/locale/', 'GNOME_SHELL_SESSION_MODE': 'ubuntu', 'DESKTOP_SESSION': 'ubuntu', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop', 'PKG_CONFIG_PATH': '/home/m123/metavision_ros_driver_ws/devel/lib/pkgconfig:/opt/ros/melodic/lib/pkgconfig', 'ROS_PACKAGE_PATH': '/home/m123/metavision_ros_driver_ws/src/dvs_msgs:/home/m123/metavision_ros_driver_ws/src/event_array_msgs:/home/m123/metavision_ros_driver_ws/src/prophesee_event_msgs:/home/m123/metavision_ros_driver_ws/src/metavision_ros_driver:/opt/ros/melodic/share', 'XDG_CURRENT_DESKTOP': 'ubuntu:GNOME', 'XDG_SESSION_ID': '2', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', '_': '/opt/ros/melodic/bin/roslaunch', 'GTK_MODULES': 'gail:atk-bridge', 'GTK_IM_MODULE': 'ibus', 'LD_LIBRARY_PATH': '/home/m123/metavision_ros_driver_ws/devel/lib:/opt/ros/melodic/lib', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/etc/xdg', 'GNOME_TERMINAL_SERVICE': ':1.315', 'VTE_VERSION': '5202', 'XDG_SESSION_TYPE': 'x11', 'OLDPWD': '/home/m123', 'LC_TELEPHONE': 'ar_AE.UTF-8', 'SHLVL': '1', 'PWD': '/home/m123/metavision_ros_driver_ws', 'ROS_MASTER_URI': 'http://localhost:11311', 'ROS_VERSION': '1', 'LC_NAME': 'ar_AE.UTF-8', 'XDG_MENU_PREFIX': 'gnome-', 'LC_TIME': 'ar_AE.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'CONDA_EXE': '/home/m123/anaconda3/bin/conda', 'XDG_SEAT': 'seat0'}]
[roslaunch][INFO] 2022-07-27 17:36:41,434: process[event_camera-2]: args[[u'/home/m123/metavision_ros_driver_ws/devel/lib/metavision_ros_driver/driver_node', u'__name:=event_camera']]
[roslaunch][INFO] 2022-07-27 17:36:41,434: ... created process [event_camera-2]
[roslaunch.pmon][INFO] 2022-07-27 17:36:41,434: ProcessMonitor.register[event_camera-2]
[roslaunch.pmon][INFO] 2022-07-27 17:36:41,434: ProcessMonitor.register[event_camera-2] complete
[roslaunch][INFO] 2022-07-27 17:36:41,434: ... registered process [event_camera-2]
[roslaunch][INFO] 2022-07-27 17:36:41,434: process[event_camera-2]: starting os process
[roslaunch][INFO] 2022-07-27 17:36:41,434: process[event_camera-2]: start w/ args [[u'/home/m123/metavision_ros_driver_ws/devel/lib/metavision_ros_driver/driver_node', u'__name:=event_camera', u'__log:=/home/m123/.ros/log/2582f37a-0db1-11ed-b622-347df657bc28/event_camera-2.log']]
[roslaunch][INFO] 2022-07-27 17:36:41,434: process[event_camera-2]: cwd will be [/home/m123/.ros]
[roslaunch][INFO] 2022-07-27 17:36:41,437: process[event_camera-2]: started with pid [20907]
[roslaunch][INFO] 2022-07-27 17:36:41,437: ... successfully launched [event_camera-2]
[roslaunch][INFO] 2022-07-27 17:36:41,437: ... launch_nodes complete
[roslaunch.pmon][INFO] 2022-07-27 17:36:41,437: registrations completed <ProcessMonitor(ProcessMonitor-1, started daemon 139747346728704)>
[roslaunch.parent][INFO] 2022-07-27 17:36:41,437: ... roslaunch parent running, waiting for process exit
[roslaunch][INFO] 2022-07-27 17:36:41,437: spin
[roslaunch][ERROR] 2022-07-27 17:36:43,282: [event_camera-2] process has died [pid 20907, exit code -11, cmd /home/m123/metavision_ros_driver_ws/devel/lib/metavision_ros_driver/driver_node __name:=event_camera __log:=/home/m123/.ros/log/2582f37a-0db1-11ed-b622-347df657bc28/event_camera-2.log].
log file: /home/m123/.ros/log/2582f37a-0db1-11ed-b622-347df657bc28/event_camera-2*.log
[roslaunch.pmon][INFO] 2022-07-27 17:36:43,282: ProcessMonitor.unregister[event_camera-2] starting
[roslaunch.pmon][INFO] 2022-07-27 17:36:43,283: ProcessMonitor.unregister[event_camera-2] complete
[roslaunch.pmon][INFO] 2022-07-27 17:37:34,428: ProcessMonitor.shutdown <ProcessMonitor(ProcessMonitor-1, started daemon 139747346728704)>
[roslaunch.pmon][INFO] 2022-07-27 17:37:34,526: ProcessMonitor._post_run <ProcessMonitor(ProcessMonitor-1, started daemon 139747346728704)>
[roslaunch.pmon][INFO] 2022-07-27 17:37:34,526: ProcessMonitor._post_run <ProcessMonitor(ProcessMonitor-1, started daemon 139747346728704)>: remaining procs are [<roslaunch.nodeprocess.LocalProcess object at 0x7f198bca1490>, <roslaunch.nodeprocess.LocalProcess object at 0x7f198bca1f50>]
[roslaunch.pmon][INFO] 2022-07-27 17:37:34,530: ProcessMonitor exit: killing rosout-1
[roslaunch][INFO] 2022-07-27 17:37:34,531: [rosout-1] killing on exit
[roslaunch][INFO] 2022-07-27 17:37:34,531: process[rosout-1]: killing os process with pid[20899] pgid[20899]
[roslaunch][INFO] 2022-07-27 17:37:34,531: [rosout-1] sending SIGINT to pgid [20899]
[roslaunch][INFO] 2022-07-27 17:37:34,531: [rosout-1] sent SIGINT to pgid [20899]
[roslaunch][INFO] 2022-07-27 17:37:34,732: process[rosout-1]: SIGINT killed with return value 0
[roslaunch.pmon][INFO] 2022-07-27 17:37:34,732: ProcessMonitor exit: killing master
[roslaunch][INFO] 2022-07-27 17:37:34,732: [master] killing on exit
[roslaunch][INFO] 2022-07-27 17:37:34,732: process[master]: killing os process with pid[20877] pgid[20877]
[roslaunch][INFO] 2022-07-27 17:37:34,732: [master] sending SIGINT to pgid [20877]
[roslaunch][INFO] 2022-07-27 17:37:34,732: [master] sent SIGINT to pgid [20877]
[roslaunch][INFO] 2022-07-27 17:37:34,933: process[master]: SIGINT killed with return value 0
[roslaunch.pmon][INFO] 2022-07-27 17:37:34,933: ProcessMonitor exit: cleaning up data structures and signals
[roslaunch.pmon][INFO] 2022-07-27 17:37:34,933: ProcessMonitor exit: pmon has shutdown
[roslaunch][INFO] 2022-07-27 17:37:34,944: process monitor is done spinning, initiating full shutdown
[roslaunch][INFO] 2022-07-27 17:37:34,944: runner.stop()
[roslaunch][INFO] 2022-07-27 17:37:34,944: shutting down processing monitor...
[roslaunch][INFO] 2022-07-27 17:37:34,945: shutting down processing monitor <ProcessMonitor(ProcessMonitor-1, stopped daemon 139747346728704)>
[roslaunch.pmon][INFO] 2022-07-27 17:37:34,945: ProcessMonitor.shutdown <ProcessMonitor(ProcessMonitor-1, stopped daemon 139747346728704)>
[roslaunch][INFO] 2022-07-27 17:37:34,945: ... shutting down processing monitor complete
[roslaunch][INFO] 2022-07-27 17:37:34,945: done
[roslaunch.pmon][INFO] 2022-07-27 17:37:34,946: ProcessMonitor.shutdown <ProcessMonitor(ProcessMonitor-1, stopped daemon 139747346728704)>
[rospy.core][INFO] 2022-07-27 17:37:34,946: signal_shutdown [atexit]

**Comment by k-chaney** [comment]
rosout.log appears to contain the start of the stream from the driver, however it does not contain the errors that were shown when the driver ultimately terminated

**Comment by berndpfrommer** [comment]
Looks like it exited with a segfault (-11)?
```
[roslaunch][ERROR] 2022-07-27 17:36:43,282: [event_camera-2] process has died [pid 20907, exit code -11, cmd /home/m123/metavision_ros_driver_ws/devel/lib/metavision_ros_driver/driver_node __name:=event_camera __log:=/home/m123/.ros/log/2582f37a-0db1-11ed-b622-347df657bc28/event_camera-2.log].
log file: /home/m123/.ros/log/2582f37a-0db1-11ed-b622-347df657bc28/event_camera-2*.log
```

**Comment by mohammedsalah98** [comment]
Yes precisely. I am not sure of how to fix this issue. Exit code -11 was on both ubuntu 18 and 20.

**Comment by mohammedsalah98** [comment]
> Looks like it exited with a segfault (-11)?
> 
> ```
> [roslaunch][ERROR] 2022-07-27 17:36:43,282: [event_camera-2] process has died [pid 20907, exit code -11, cmd /home/m123/metavision_ros_driver_ws/devel/lib/metavision_ros_driver/driver_node __name:=event_camera __log:=/home/m123/.ros/log/2582f37a-0db1-11ed-b622-347df657bc28/event_camera-2.log].
> log file: /home/m123/.ros/log/2582f37a-0db1-11ed-b622-347df657bc28/event_camera-2*.log
> ```

**Comment by mohammedsalah98** [comment]
Yes precisely. It was exit code -11 on both ubuntu 18 and 20. At the beginning I was using ubuntu 18 and was afraid that it was a problem with the linux version. But the same error persisted on ubuntu 20.

**Comment by mohammedsalah98** [comment]
When i run the launch file thats the output:

setting /run_id to 79ab13be-0dc6-11ed-b622-347df657bc28
process[rosout-1]: started with pid [23639]
started core service [/rosout]
process[event_camera-2]: started with pid [23647]
[ INFO] [1658938162.204270410]: running in message mode: event_array
[ INFO] [1658938162.205550783]: sync mode: standalone
[ INFO] [1658938162.208396677]: event message time threshold: 0.001
[ INFO] [1658938162.208686513]: using event message reserve size: 50000
[ INFO] [1658938162.209734520]: trigger message time threshold: 0
[ INFO] [1658938163.884596829]: Plugin Software Name: hal_plugin_gen41_evk2
[ INFO] [1658938163.884690992]: no bias file provided, using camera defaults
[ INFO] [1658938163.884731096]: camera serial number: Prophesee:hal_plugin_gen41_evk2:0000a24d
[ INFO] [1658938163.884767380]: sensor geometry: 1280 x 720
[HAL][WARNING] Error setting roi for Gen 41 sensor. 
[event_camera-2] process has died [pid 23647, exit code -11, cmd /home/m123/metavision_ros_driver_ws/devel/lib/metavision_ros_driver/driver_node __name:=event_camera __log:=/home/m123/.ros/log/79ab13be-0dc6-11ed-b622-347df657bc28/event_camera-2.log].
log file: /home/m123/.ros/log/79ab13be-0dc6-11ed-b622-347df657bc28/event_camera-2*.log
^C[rosout-1] killing on exit
[master] killing on exit
^Cshutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by berndpfrommer** [comment]
I just pushed a fix for the first problem: the complaints about the metavision.cfg file:
```
SyntaxError: Non-ASCII character '\xe2' in file /home/m123/metavision_ros_driver_ws/src/metavision_ros_driver/cfg/MetaVisionDyn.cfg on line 14, but no encoding declared;
```
I believe the reason we did not receive an error message regarding the non-ascii characters is because our systems are set up to handle UTF-8 encoding, yours is not.

I would assume that the segfault is not related to this, but it potentially it could. Anyways, please pull the driver again and see if it gets rid of the non-ascii character error.

**Comment by mohammedsalah98** [comment]
Thank you. It compiled now but still the launch file error persists. I tried to run the node with rosrun, it gave me segmentation fault (core dumped).

**Comment by berndpfrommer** [comment]
About the segfault: could you please launch the driver under the gdb debugger. You will have to hack the launch file as described here:

http://wiki.ros.org/roslaunch/Tutorials/Roslaunch%20Nodes%20in%20Valgrind%20or%20GDB 

Can you let us know what the stack trace looks like? It usually shows when it drops you into the debugger, but in case it doesn't , use the gdb "where" command.
 
BTW, there is a preceeding error message from the HAL about setting the ROI. After you are done with taking the stack trace (but only then :), try removing any ROI settings in your launch file and see if that fixes the problem.

**Comment by mohammedsalah98** [comment]
Here is the output from valgrind:
[valgrind_report.txt](https://github.com/berndpfrommer/metavision_ros_driver/files/9201476/valgrind_report.txt)

**Comment by berndpfrommer** [comment]
I was hoping to get gdb, not valgrind output, so you need to put something like this among the node tags:
```
<node name="talker" pkg="roscpp_tutorials" type="talker" launch-prefix="xterm -e gdb --args"/>
```

**Comment by mohammedsalah98** [comment]
Hello, actually I have fixed the issue, it was as you mentioned the roi error. There was a syntax error in the launch file with the line of the roi. Thank you very much for the help. One small final concern about the timestamps, I need to have the events to be timestamped at the clock of the workstation and not the camera. Is this done automatically by the driver? I did not get that part in the README.
Thanks!

**Comment by mohammedsalah98** [comment]
Launch file fix:
<launch>
  <arg name="bias_file" default=""/>
  <node pkg="metavision_ros_driver" type="driver_node" name="event_camera" clear_params="true"
	output="screen">
    
    <param name="use_multithreading" value="true"/>
    
    <param name="event_message_time_threshold" value="0.001"/>
    
    <param name="trigger_message_time_threshold" value="0"/>
    <param name="trigger_out_mode" value="enabled"/>
    
    <param name="trigger_out_period" value="1000"/>
    <param name="trigger_out_duty_cycle" value="0.5"/>
    <param name="trigger_in_mode" value="loopback"/>
    
    <param name="statistics_print_interval" value="1.0"/>
    
    <param name="bias_file" value=""/>
    
    <param name="message_type" value="dvs"/>
    
    <rosparam param="roi">[0, 0, 1280, 720]</rosparam>
    
    <rosparam command="load" file="$(find metavision_ros_driver)/config/trigger_pins.yaml"/>
  </node>
</launch>

**Comment by mohammedsalah98** [comment]
Launch file fix:

<launch>
  <arg name="bias_file" default=""/>
  <node pkg="metavision_ros_driver" type="driver_node" name="event_camera" clear_params="true"
	output="screen">
    
    <param name="use_multithreading" value="true"/>
    
    <param name="event_message_time_threshold" value="0.001"/>
    
    <param name="trigger_message_time_threshold" value="0"/>
    <param name="trigger_out_mode" value="enabled"/>
    
    <param name="trigger_out_period" value="1000"/>
    <param name="trigger_out_duty_cycle" value="0.5"/>
    <param name="trigger_in_mode" value="loopback"/>
    
    <param name="statistics_print_interval" value="1.0"/>
    
    <param name="bias_file" value=""/>
    
    <param name="message_type" value="dvs"/>
    
    <rosparam param="roi">[0, 0, 1280, 720]</rosparam>
    
    <rosparam command="load" file="$(find metavision_ros_driver)/config/trigger_pins.yaml"/>
  </node>
</launch>

**Comment by mohammedsalah98** [comment]
Launch file fix:
[launch_fix.txt](https://github.com/berndpfrommer/metavision_ros_driver/files/9203899/launch_fix.txt)

**Comment by berndpfrommer** [comment]
To answer your question:
1) The time stamp in header.stamp is the one of the *host*. This morning @k-chaney discovered a bug that I'm currently investigating, which causes the time stamps to be off. The bug is somewhat hard to reproduce and I was so far only able to trigger it when the subscriber starts *before* the driver. So avoid that scenario and you should be good.
2) Please use the event_array_msgs, *not* dvs or prophesee msgs. Not only will you get better performance, but also when you use event_array_msgs, you can recover sensor time as well via the time_base field. This is not possible with dvs or prophesee message types.

Another thing: could you post the launch file that caused the crash? Just so I can make the driver not bomb out with a segfault when a bad config file is used.

**Comment by mohammedsalah98** [comment]
The launch file that caused the crash is the driver_node.launch. The fixed file is in the previous comment.
Thanks a lot!

**Comment by mohammedsalah98** [comment]
But regarding the timestamps, for all the messages, the timestamp of the host is always reported, if the sensor time is needed then the event_array_msgs should be used right?

**Comment by berndpfrommer** [comment]
There are principally 3 different time stamps here:
1) The host time stamp when the data was ultimately received by the subscriber. In a rosbag, this will be called "recording time" and is readable as part of the rosbag API.
2) The header stamp of the event_array message (header.stamp). This is supposed to be the host time stamp when the data arrived but it is not quite because I didn't like the large amount of jitter that is typically associated with just reading the host clock whenever a packet gets delivered from the Metavision SDK. So presently it is actually the sensor clock, shifted to the host clock. As such it looks and feels like the host clock, but it has much less jitter in particular when the host is under CPU load.
3) The sensor time stamp. This one can be recovered by using the ``time_base`` field of the message. You will get the original sensor time back, which is roughly the time since the camera was started. For example code on how to decode event_array_msgs and recover original sensor time please see: https://github.com/berndpfrommer/event_array_msgs/tree/master/python

**Comment by berndpfrommer** [comment]
NOTICE: I have just pushed a set of new commits for the metavision_ros_driver. This should make the ROS time stamps much more robust to the weirdness that we've been seeing on startup with the SIlkyEVCam. More importantly, the driver now spits out warning messages should the sensor time stamps be wonky. I strongly urge everybody to pull these fixes.

Also there is a new repo now that has a "perf" tool to measure the time difference between header stamp and arrival time stamp. Run this tool and look at the "delay" to make sure the ROS time stamps are good.

https://github.com/berndpfrommer/event_array_tools

**Comment by berndpfrommer** [comment]
@mohammedsalah98 the original driver_node.launch file had the ROI commented out so I'm surprised the driver crashed with an ROI error message. I'm still interested in the stack trace for this crash.

**Comment by berndpfrommer** [comment]
no reply, original issue has been addressed, closing
